version: '2'
services:
  election1:
    build: .
    environment:
      server.port: 0
      spring.cloud.cluster.zookeeper.connect: zookeeper:2181
    links:
      - zookeeper
  election2:
    build: .
    environment:
      server.port: 0
      spring.cloud.cluster.zookeeper.connect: zookeeper:2181
    links:
      - zookeeper
  zookeeper:
    image: jplock/zookeeper:3.4.9
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
